### ISSUE TITLE
[Logic] Add conversion function for logic formulas to existential disjunctive normal form

### ISSUE THREAD

**Issue by elvilio** [Alex23087/LIS-Project#20]
Convert all logic formulas to normal form that uses only existentials and disjunctions following using the equivalences:
- (p or q) * t == (p * t) or (q * t)
- (exists x. p) * q == exists x. (p*q) where (x is not in the free variables of q)
- equivalences of the first order logic

_Note that the existential quantification is external with respect to the disjoints._

**Comment by Yurand2000** [comment]
TO DO:
- [ ] More tests
- [ ] Tests: Translate formulas from data structure style to real code style (which will be parsed), for better readability.
